from playwright.sync_api import Page

class HomePage:
    def __init__(self, page: Page):
        self.page = page

    def check_project_name(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        a1 = self.page.text_content("//label[text()='Archivista interiors']")
        a = "Archivista interiors"
        assert a == a1


    def check_1project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[2]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[2]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[2]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_2project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[3]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[3]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[3]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H
    def check_3project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[4]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[4]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[4]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H
    def check_4project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[5]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[5]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[5]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H
    def check_5project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[6]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[6]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[6]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H
    def check_6project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[7]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[7]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[7]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_7project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[8]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[8]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[8]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_8project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[9]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[9]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[9]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_9project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[10]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[10]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[10]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_10project(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='quantity'])[11]")
        a = a1.replace(',', '').strip()
        print(a)
        c1 = self.page.text_content("(//td[@id='rate'])[11]")
        c = c1.replace(',', '').strip()
        print(c)
        e1 = self.page.text_content("(//td[@id='total'])[11]")
        e = e1.replace(',', '').strip()
        print(type(e))
        E = float(e)
        F = float(a)
        G = float(c)
        H = G*F
        assert E == H

    def check_total(self):
        self.page.get_by_role("link", name="Projects").click()
        self.page.get_by_role("heading", name="Rate analysis of furniture").locator("span").click()
        self.page.get_by_role("cell", name="Q001").locator("a").click()
        self.page.get_by_text("Archivista interiors", exact=True).click()
        self.page.get_by_text("OPT 1- Providing & making").click()
        a1 = self.page.text_content("(//td[@id='total'])[2]")
        a = a1.replace(',', '').strip()
        b1 = self.page.text_content("(//td[@id='total'])[3]")
        b = b1.replace(',', '').strip()
        c1 = self.page.text_content("(//td[@id='total'])[4]")
        c = c1.replace(',', '').strip()
        d1 = self.page.text_content("(//td[@id='total'])[5]")
        d = d1.replace(',', '').strip()
        e1 = self.page.text_content("(//td[@id='total'])[6]")
        e = e1.replace(',', '').strip()
        f1 = self.page.text_content("(//td[@id='total'])[7]")
        f = f1.replace(',', '').strip()
        g1 = self.page.text_content("(//td[@id='total'])[8]")
        g = g1.replace(',', '').strip()
        h1 = self.page.text_content("(//td[@id='total'])[9]")
        h = h1.replace(',', '').strip()
        i1 = self.page.text_content("(//td[@id='total'])[10]")
        i = i1.replace(',', '').strip()
        j1 = self.page.text_content("(//td[@id='total'])[11]")
        j = j1.replace(',', '').strip()
        print(type(e))
        A = float(a)
        print(A)
        B = float(b)
        print(B)
        C = float(c)
        print(C)
        D = float(d)
        print(D)
        E = float(e)
        print(E)
        F = float(f)
        print(F)
        G = float(g)
        print(G)
        H = float(h)
        print(H)
        I = float(i)
        print(I)
        J = float(j)
        print(J)
        H = A+B+C+D+E+F+G+H+I+J
        k1 = self.page.text_content("(//td[@id='total'])[1]")
        k2 = k1.replace(',', '').strip()
        k = k2.replace('₹ ', '').strip()
        K = float(k)
        print(K)

        assert K == H